### ISSUE TITLE
Add support for structures or case class

### ISSUE THREAD

**Issue by Zorvalt** [Willumz/generic-pseudocode-vscode#1]
Hi,

I find your extension really useful and I would like to have support for a sort of struct keyword to express the idea of pure storage as opposed to classes.

Do you think you could add this easily ?

A simple way to implement this would be by changing the class regex from "... class ..." to "... (class|struct) ..."

My use case would be to express network messages or another storage without any associated behavior.

**Comment by willumz** [comment]
Thanks for your input @Zorvalt. I'm happy to hear it's helped you.
You were right in saying adding structs was an easy task, so I've gone ahead and done it (and added the appropriate snippets while I was at it). I hope that helps.

**Comment by Zorvalt** [comment]
Thank you! :-)
