### ISSUE TITLE
Comments are sometimes undetected in classes

### ISSUE THREAD

**Issue by ferancona** [Willumz/generic-pseudocode-vscode#11]
![image](https://user-images.githubusercontent.com/31116930/146577230-6ca35d27-3cb8-4dbf-92e3-1739fc8d7281.png)
![image](https://user-images.githubusercontent.com/31116930/146577274-0b5b3df7-42ea-4c72-9e8c-f33652e84a6b.png)

**Comment by willumz** [comment]
Sorry it took me so long to get round to this. I've had a look and fixed this issue (in ecdcef6). I'm not able to rebuild and push to the extension marketplace right now, but I will do later.
