### ISSUE TITLE
Making default Keywords uppercase

### ISSUE THREAD

**Issue by ericsia** [Willumz/generic-pseudocode-vscode#12]
is it possible you make the default keywords all uppercase?
I can help to issue pull request to the snipets if you are ok with this

**Comment by heylael** [comment]
We would also be very much interested in this (or the ability to overwrite the keywords with uppercase in the .pseudoconfig file - and an example file to be used if possible). 

Thanks - love your work!

**Comment by willumz** [comment]
Apologies for taking so long to look into this. Unfortunately I don't think it's possible to change snippets dynamically (like @heylael suggests) meaning the only option would be to either replace the existing snippets or create new ones. I am potentially open to replicating all current snippets with a prefix (something like 'u') for uppercase variants. I'm busy right now but I'll work on that later in the week.
