### ISSUE TITLE
Custom keywords and syntaxing

### ISSUE THREAD

**Issue by spdfNerd** [Willumz/generic-pseudocode-vscode#4]
Hello! This extension has been absolutely great for writing pseudocode so far. However, I feel like there should be settings that allow users to add custom keywords if they want to, as there are no standards for pseudocode syntaxing, and the highlighting should extend to those custom keywords. Thank you in advance!

**Comment by nik312123** [comment]
I very much agree with this. Having some location in which custom words for each color can be put would be phenomenal.

The Code Spell Check extension is a great example of this. Here is their VS Code page (https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker), and here is there GitHub page (https://github.com/streetsidesoftware/vscode-spell-checker).

**Comment by willumz** [comment]
Sorry it took me so long to get round to this! I've looked into methods of achieving this feature and am working on it.
Thanks for the great suggestion!
