### ISSUE TITLE
Custom keywords are highlighted in comments

### ISSUE THREAD

**Issue by jeremymouzin** [Willumz/generic-pseudocode-vscode#9]
Steps to reproduce the bug:

1. Create `.pseudoconfig` file in home directory with following content:
```js
{
  "custom": {
    "keyword": [
       "damn"
    ]
  }
}
```
2. Create a new `test.pseudo` file with the following content:
```
// This is a comment. This damn word shouldn't be highlighted!
```

The result is that the damn word in the comment is highlighted while it should not.
The predefined keyword shipped with the extension doesn't highlight in comments.

**Comment by willumz** [comment]
Thanks for reporting this bug. I've pushed a fix for it so hopefully that'll solve the issue. Let me know if you continue experiencing related problems. 👍🏻

**Comment by javascriptdezero** [comment]
You're welcome! Thanks for your quick answer. I can confirm this bug is fixed on my side 👍
